"""add_user_asset_set_and_extra

Revision ID: 630ff0126d08
Revises: b29d09a723ca
Create Date: 2025-12-08 00:17:46.276526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '630ff0126d08'
down_revision = 'b29d09a723ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('asset_set_id', sa.UUID(), nullable=True))
    op.add_column('user', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(op.f('fk_user_asset_set_id_asset_set'), 'user', 'asset_set', ['asset_set_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_asset_set_id_asset_set'), 'user', type_='foreignkey')
    op.drop_column('user', 'extra')
    op.drop_column('user', 'asset_set_id')
    # ### end Alembic commands ###
