"""init

Revision ID: 8c8d47a414c0
Revises: 
Create Date: 2025-12-05 18:46:30.298900

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c8d47a414c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # Ensure extension is created for GIN/TRGM
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_statuses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_statuses')),
    sa.UniqueConstraint('name', name=op.f('uq_asset_statuses_name'))
    )
    op.create_table('asset_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_types')),
    sa.UniqueConstraint('name', name=op.f('uq_asset_types_name'))
    )
    op.create_table('integration',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration'))
    )
    op.create_table('job',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('import_assets', 'sync_integration', 'ai_task', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='jobstatus'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job'))
    )
    op.create_table('permission',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_permission'))
    )
    op.create_table('role',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_role'))
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('asset_set',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_asset_set_created_by_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset_set'))
    )
    op.create_table('auditlog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_auditlog_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditlog'))
    )
    op.create_table('request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'closed', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], name=op.f('fk_request_requester_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request'))
    )
    op.create_table('role_permissions',
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('permission_slug', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_slug'], ['permission.slug'], name=op.f('fk_role_permissions_permission_slug_permission')),
    sa.ForeignKeyConstraint(['role_name'], ['role.name'], name=op.f('fk_role_permissions_role_name_role')),
    sa.PrimaryKeyConstraint('role_name', 'permission_slug', name=op.f('pk_role_permissions'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['role_name'], ['role.name'], name=op.f('fk_user_roles_role_name_role'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_user_roles_user_id_user'), ondelete='CASCADE')
    )
    op.create_table('asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=True),
    sa.Column('asset_set_id', sa.UUID(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('assigned_user_id', sa.UUID(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status_id', sa.UUID(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_set_id'], ['asset_set.id'], name=op.f('fk_asset_asset_set_id_asset_set'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], name=op.f('fk_asset_asset_type_id_asset_types'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['user.id'], name=op.f('fk_asset_assigned_user_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['asset_statuses.id'], name=op.f('fk_asset_status_id_asset_statuses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asset')),
    sa.UniqueConstraint('serial_number', name=op.f('uq_asset_serial_number'))
    )
    op.create_index('ix_asset_trgm', 'asset', ['name', 'serial_number', 'location'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops', 'serial_number': 'gin_trgm_ops', 'location': 'gin_trgm_ops'})
    op.create_table('custom_field_definition',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('asset', 'user', name='customfieldtarget'), nullable=False),
    sa.Column('asset_type_id', sa.UUID(), nullable=True),
    sa.Column('asset_set_id', sa.UUID(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.Enum('string', 'integer', 'boolean', 'date', 'enum', 'reference', name='customfieldtype'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_set_id'], ['asset_set.id'], name=op.f('fk_custom_field_definition_asset_set_id_asset_set'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], name=op.f('fk_custom_field_definition_asset_type_id_asset_types'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_definition'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_field_definition')
    op.drop_index('ix_asset_trgm', table_name='asset', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops', 'serial_number': 'gin_trgm_ops', 'location': 'gin_trgm_ops'})
    op.drop_table('asset')
    op.drop_table('user_roles')
    op.drop_table('role_permissions')
    op.drop_table('request')
    op.drop_table('auditlog')
    op.drop_table('asset_set')
    op.drop_table('user')
    op.drop_table('role')
    op.drop_table('permission')
    op.drop_table('job')
    op.drop_table('integration')
    op.drop_table('asset_types')
    op.drop_table('asset_statuses')
    # ### end Alembic commands ###
