"""add request type and asset to requests

Revision ID: b29d09a723ca
Revises: f04deac99ce6
Create Date: 2025-12-07 20:56:21.360462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b29d09a723ca'
down_revision = 'f04deac99ce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('asset_id', sa.UUID(), nullable=True))
    
    # Create enum type explicitly
    request_type = postgresql.ENUM('new_asset', 'assigned_asset', 'other', name='requesttype')
    request_type.create(op.get_bind())
    
    op.add_column('request', sa.Column('request_type', sa.Enum('new_asset', 'assigned_asset', 'other', name='requesttype'), nullable=False, server_default='other'))
    op.create_foreign_key(op.f('fk_request_asset_id_asset'), 'request', 'asset', ['asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_request_asset_id_asset'), 'request', type_='foreignkey')
    op.drop_column('request', 'request_type')
    
    # Drop enum type explicitly
    request_type = postgresql.ENUM('new_asset', 'assigned_asset', 'other', name='requesttype')
    request_type.drop(op.get_bind())
    
    op.drop_column('request', 'asset_id')
    # ### end Alembic commands ###
