"""add_budget_and_lifecycle_fields

Revision ID: d3a40f900074
Revises: c15cbb2beb5a
Create Date: 2025-12-22 17:15:08.801314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a40f900074'
down_revision = 'c15cbb2beb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset', sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('asset', sa.Column('purchase_date', sa.Date(), nullable=True))
    op.add_column('asset', sa.Column('vendor', sa.String(), nullable=True))
    op.add_column('asset', sa.Column('order_number', sa.String(), nullable=True))
    op.add_column('asset', sa.Column('warranty_end', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('employment_end_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'employment_end_date')
    op.drop_column('asset', 'warranty_end')
    op.drop_column('asset', 'order_number')
    op.drop_column('asset', 'vendor')
    op.drop_column('asset', 'purchase_date')
    op.drop_column('asset', 'purchase_price')
    # ### end Alembic commands ###
